### ISSUE TITLE
Cannot reach inbo.r-universe.dev

### ISSUE THREAD

**Issue by peterdesmet** [inbo/universe#6]
When trying to reach https://inbo.r-universe.dev from my Macbook (over home network), I get:

> This site can’t be reached
> inbo.r-universe.dev’s server IP address could not be found.

This is the case in all browsers (Chrome, Safari, Firefox).

Oddly enough, does work via my phone (over the same network).

Any idea what might be the issue?

**Comment by ElsLommelen** [comment]
Strange, I can open it in Chrome in both Windows and Linux (Ubuntu), and in Firefox in Ubuntu.

Internet Explorer (Windows) tries to load the 'build data' or 'articles' (depending on the selected tab above, which is loaded) for quite some time (too long to wait for). So it seems IE has some problems with the site as well, but only with loading the lists with packages and vignettes (the tabs, column heads and navigation buttons are shown).

Any other OS-browser-combinations to add, Firefox on Windows maybe (I don't have it installed)?  ;-)
